server:
  port: 8080
  servlet:
    context-path: /TravelShare

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/TravelShare}
    driverClassName: "org.postgresql.Driver"
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD} #App password (Gmail)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 604800 # in seconds

app:
  invitation:
    base-url: http://localhost:8080/TravelShare/api/v1/invitation
  file:
    storage-dir: D:\Project\Backend\TravelShare\src\main\resources\static\upload
    download-prefix: http://localhost:8080/TravelShare/media/download/
  admin:
    username: admin
    password: ${ADMIN_PASSWORD}
    email: admin@travelshare.com
  email:
    from: noreply@travelshare.com
    verification-base-url: http://localhost:8080/TravelShare/auth/verify-email
    reset-password-base-url: http://localhost:8080/TravelShare/auth/reset-password
    verification-expiration: 24  #Hours

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/TravelShare/settlement/vnpay/callback
  ipn-url: http://localhost:8080/TravelShare/settlement/vnpay/ipn